### PR TITLE
Enum feature

### PR DESCRIPTION
**Pull request by EroAuditore**
### Enum functions to validate

- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map
- my_inject
- multiply_els

### CODE REVIEW

**Review by LamiaSristy — COMMENTED** [review]
# Status: Invalid Review Request ✖️ 🔴 

Hello, @EroAuditore  and @Rashad-Muntar.

I can see a lot of efforts and dedication here, but unfortunately, I have to mark this review request as invalid. 😢 😢 

👉 **You need to set up linters correctly in your code and all your GitHub Actions checks need to be successful.**

👉 **Currently it is showing 0 checks are done**

## How to solve this issue: 

- [x] Please read the full `linters` specifications from [here](https://github.com/microverseinc/linters-config/tree/master/ruby).

- [x] Please add `.github/workflows/linters.yml` file in your project's root directory. you can check [here](https://github.com/microverseinc/linters-config/blob/master/ruby/.github/workflows/linters.yml).

Once you add the linters correctly and all the GitHub Actions checks become successful, then please ask again for a CRR.

**Keep Up the spirit always**

Feel free to reach me on slack @lamiasristy 🙋

Happy Coding 💻

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes required** :red_circle: 
Hello :hand: 

Good introduction. However, there are bugs to fix.

- [x]  [ REQUIRED ] #my_each returns an Enumerator if no block is given

- [x]  [ REQUIRED ] #my_each when a block is given when self is an array returns the array itself after calling the given block once for each element in self

- [x]  [ REQUIRED ] #my_each when a block is given when self is a range returns the range itself after calling the given block once for each element in self

- [x]  [ REQUIRED ] #my_each when a block is given when self is a range behaves like #each calls the given block once for each element in self

- [x]  [ REQUIRED ] #my_each_with_index returns an enumerator if no block is given

- [x]  [ REQUIRED ] #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self

- [x]  [ REQUIRED ] #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self

- [x]  [ REQUIRED ] #my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self

- [x]  [ REQUIRED ] #my_select returns an array containing all elements of enum for which the given block returns a true value::range

- [x]  [ REQUIRED ] #my_select returns an enumerator if no block is given

- [x]  [ REQUIRED ] #my_all? returns false if the block returns false or nil::range

- [x]  [ REQUIRED ] #my_all? when no block or argument is given returns false when one of the collection members are false or nil

- [x]  [ REQUIRED ] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer

- [x]  [ REQUIRED ] #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric

- [x]  [ REQUIRED ] #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class

- [x]  [ REQUIRED ]  #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

- [x]  [ REQUIRED ] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

- [x]  [ REQUIRED ]  #my_any? returns false if the block ever returns a value false or nil::range

- [x]  [ REQUIRED ] #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil

- [x]  [ REQUIRED ] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric

- [x]  [ REQUIRED ] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer

- [x]  [ REQUIRED ] #my_none? returns false if the block ever returns true for all elements::range

- [x]  [ REQUIRED ] #my_none? when no block or argument is given returns false only if one of the collection members is true

- [x]  [ REQUIRED ] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class

- [x]  [ REQUIRED ] #my_none? when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric

- [x]  [ REQUIRED ] #my_none? when a class is passed as an argument returns false if any of the collection is a member of such class

- [x]  [ REQUIRED ] #my_none? when a Regex is passed as an argument returns true if none of the collection matches the Regex

- [x]  [ REQUIRED ] #my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex

- [x]  [ REQUIRED ] #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

- [x]  [ REQUIRED ] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

- [x]  [ REQUIRED ] #my_count returns the number of items in enum through enumeration::range

- [x]  [ REQUIRED ] #my_map returns an Enumerator if no block is given

- [x]  [ REQUIRED ] #my_inject raises a "LocalJumpError" when no block or argument is given

- [x]  [ REQUIRED ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method

- [x]  [ REQUIRED ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range

Kindly make the changes and submit a new code review request.
Thanks

Rindra Josia

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @EroAuditore, your progress is commendable, more than 80% of the tests are passing.
Let's make a few changes, and we will be done.

- [x] `#my_each_with_index` when a block is given when self is a range returns the range itself after calling the given block once for each element in self `expect(range.my_each_with_index(&block)).to eq(range.each_with_index(&block))` It throws an error `undefined local variable or method `length' for 5..50:Range`
- [x]  `#my_any?` when no block or argument is given returns false if at least one of the collection is not true  `expect(false_array.my_any?).to be false_array.any?`
- [x] `#my_any?` when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern. `%w[dog door rod blade].my_none?('cat')).to be %w[dog door rod blade].any?('cat')`
- [x] `#my_none?` when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern `expect(%w[dog door rod blade].my_none?(5)).to be %w[dog door rod blade].none?(5)`
- [x] `#my_count ` returns the number of items in enum through enumeration `[1,2,3].my_count` should return 3
- [x] `#my_count` returns the number of items in enum through enumeration::range `Range.new(5, 50).my_count` should return 46
- [x] `#my_count ` counts the number of items in enum that are equal to the item if an argument is given `[1,2,3,4,1].count(1)` should return 2
- [x] `#my_count` counts the number of elements yielding a true value if a block is given `expect(array.my_count(&block)).to eq array.count(&block)`
- [x] `#my_inject` when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range  `(2..5).inject(:*)` should return 120

Make these changes and request for another code review

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Congratulations @EroAuditore on completing your project and taking the time to implement the requested changes.

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
